name: 'Run App Garrett Wilcoxen'

on: [push, pull_request]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore GithubActions.sln
      - name: Build
        run: dotnet build GithubActions.sln --configuration Release
